### PR TITLE
✨ emoji button made optional

### PR DESCRIPTION
**Pull request by mattmezza**
#47 

I made the emoji button optional for the non emoji fans (which I hate so much 😡)

### CODE REVIEW

**Comment by dharness** [comment]
Nice and clean! Much appreciated. Can you just update the README in the PR to add the prop?

Otherwise lgtm.

**Comment by mattmezza** [comment]
Did it 👍 
Thanks for the great library.

**Comment by mattmezza** [comment]
Heya, is there any chance to get this changes into a new release? I wanna `yarn upgrade` to get the awesomeness 😎

**Comment by dharness** [comment]
Should be good with v1.0.6!

**Pull request merged**
